name: eco_monitor
description: A Flutter implementation of SmartFloor dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  http: ^1.1.0

flutter_launcher_icons:
  # --- Configuración Multiplataforma ---
  android: true        # Generar íconos para Android
  ios: true            # Generar íconos para iOS
  
  web:
    generate: true     # Generar íconos para Web
  
  windows:
    generate: true     # Generar íconos para Windows
  
  macos:
    generate: true     # Generar íconos para macOS

  # --- Ruta a tu imagen ---
  # Asegúrate de que esta ruta coincida con donde guardaste tu imagen
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
